export const fallbackSettings = {
  id: "default",
  title: "Jebaz Wesley Raj",
  subtitle: "Full Stack Developer",
  description: "Premium portfolio website of Jebaz Wesley Raj",
  keywords: "portfolio, developer, full stack, react, next.js",
  profileImage: null,
  resumeUrl: null,
  heroTitle: "Jebaz Wesley Raj",
  heroSubtitle: "Software Developer & AI Enthusiast",
  heroBackground: null,
  aboutTitle: "About Me",
  aboutBio:
    "I'm a passionate software developer focused on building modern web applications, AI-powered solutions, and interactive digital experiences. I love turning complex problems into clean, elegant code that delivers real value.",
  aboutEducation:
    "Computer Science graduate with a deep focus on full-stack development, system design, and artificial intelligence. Constantly learning and pushing the boundaries of what's possible with technology.",
  aboutGoals:
    "To build products that make a difference. I'm passionate about leveraging AI and modern web technologies to create solutions that are both powerful and accessible.",
  githubUrl: "https://github.com/jebazwesley",
  linkedinUrl: "https://linkedin.com/in/jebazwesley",
  twitterUrl: null,
  email: "jebazwesleyraj@gmail.com",
  phone: null,
  location: "India",
  primaryColor: "#D4AF37",
  updatedAt: new Date(),
};

export const fallbackProjects = [
  {
    id: "proj-1",
    title: "E-Commerce Platform",
    slug: "e-commerce-platform",
    description:
      "A full-featured e-commerce platform with product management, shopping cart, Stripe payment integration, and an admin dashboard. Built with modern web technologies for scalability and performance.",
    content: null,
    challenges: null,
    technologies: ["React", "Next.js", "TypeScript", "PostgreSQL", "Stripe"],
    githubUrl: "https://github.com/jebazwesley/ecommerce",
    demoUrl: null,
    featured: true,
    order: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: "proj-2",
    title: "AI Chat Application",
    slug: "ai-chat-application",
    description:
      "Real-time AI-powered chat application with natural language processing, WebSocket communication, and a responsive UI. Integrates with LLM APIs for intelligent conversations.",
    content: null,
    challenges: null,
    technologies: ["Python", "FastAPI", "React", "WebSocket", "OpenAI"],
    githubUrl: "https://github.com/jebazwesley/ai-chat",
    demoUrl: null,
    featured: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: "proj-3",
    title: "Portfolio Website",
    slug: "portfolio-website",
    description:
      "A premium, animated portfolio website built with Next.js, featuring a CMS-driven architecture, admin dashboard, and recruiter-focused design.",
    content: null,
    challenges: null,
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Prisma"],
    githubUrl: "https://github.com/jebazwesley/portfolio",
    demoUrl: null,
    featured: false,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: "proj-4",
    title: "Task Management App",
    slug: "task-management-app",
    description:
      "A collaborative task management application with real-time updates, drag-and-drop kanban board, team workspaces, and notification system.",
    content: null,
    challenges: null,
    technologies: ["React", "Node.js", "MongoDB", "Socket.io", "Redis"],
    githubUrl: "https://github.com/jebazwesley/task-manager",
    demoUrl: null,
    featured: false,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
];

export const fallbackSkillCategories = [
  {
    id: "cat-1",
    name: "Frontend",
    order: 0,
    skills: [
      { id: "skill-1", name: "React", level: 95, icon: null, order: 0 },
      { id: "skill-2", name: "Next.js", level: 92, icon: null, order: 1 },
      { id: "skill-3", name: "TypeScript", level: 90, icon: null, order: 2 },
      { id: "skill-4", name: "HTML/CSS", level: 95, icon: null, order: 3 },
      { id: "skill-5", name: "JavaScript", level: 93, icon: null, order: 4 },
      { id: "skill-6", name: "Tailwind CSS", level: 88, icon: null, order: 5 },
    ],
  },
  {
    id: "cat-2",
    name: "Backend",
    order: 1,
    skills: [
      { id: "skill-7", name: "Node.js", level: 88, icon: null, order: 0 },
      { id: "skill-8", name: "Python", level: 80, icon: null, order: 1 },
      { id: "skill-9", name: "PostgreSQL", level: 82, icon: null, order: 2 },
      { id: "skill-10", name: "Prisma", level: 85, icon: null, order: 3 },
      { id: "skill-11", name: "REST APIs", level: 90, icon: null, order: 4 },
      { id: "skill-12", name: "GraphQL", level: 75, icon: null, order: 5 },
    ],
  },
  {
    id: "cat-3",
    name: "Tools & Others",
    order: 2,
    skills: [
      { id: "skill-13", name: "Git", level: 90, icon: null, order: 0 },
      { id: "skill-14", name: "Docker", level: 75, icon: null, order: 1 },
      { id: "skill-15", name: "AWS", level: 70, icon: null, order: 2 },
      { id: "skill-16", name: "CI/CD", level: 78, icon: null, order: 3 },
      { id: "skill-17", name: "Figma", level: 72, icon: null, order: 4 },
      { id: "skill-18", name: "Linux", level: 80, icon: null, order: 5 },
    ],
  },
];

export const fallbackExperience = [
  {
    id: "exp-1",
    company: "Freelance / Self-Employed",
    role: "Full Stack Developer",
    description:
      "Building modern web applications for clients using Next.js, TypeScript, and Node.js. Leading architecture decisions, implementing CI/CD pipelines, and delivering production-ready solutions.",
    startDate: new Date("2023-01-01"),
    endDate: null,
    current: true,
    type: "work",
    location: "Remote",
    order: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "exp-2",
    company: "Tech Startup",
    role: "Frontend Developer Intern",
    description:
      "Developed responsive React components, integrated REST APIs, and contributed to the company's main SaaS product. Worked in an agile team environment with weekly sprint cycles.",
    startDate: new Date("2022-06-01"),
    endDate: new Date("2022-12-01"),
    current: false,
    type: "internship",
    location: "India",
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "exp-3",
    company: "University",
    role: "B.S. Computer Science",
    description:
      "Focused on data structures, algorithms, web development, database systems, and software engineering. Graduated with honors and completed a capstone project in full-stack development.",
    startDate: new Date("2019-09-01"),
    endDate: new Date("2023-05-01"),
    current: false,
    type: "education",
    location: null,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const fallbackCertifications = [
  {
    id: "cert-1",
    title: "AWS Certified Developer – Associate",
    issuer: "Amazon Web Services",
    description: "Validated expertise in developing and maintaining AWS-based applications.",
    imageUrl: null,
    pdfUrl: null,
    verificationUrl: "https://aws.amazon.com/certification/",
    issueDate: new Date("2024-03-01"),
    expiryDate: null,
    order: 0,
    createdAt: new Date(),
  },
  {
    id: "cert-2",
    title: "Meta Front-End Developer",
    issuer: "Meta (Coursera)",
    description: "Professional certificate covering React, UI frameworks, and front-end development best practices.",
    imageUrl: null,
    pdfUrl: null,
    verificationUrl: "https://coursera.org/",
    issueDate: new Date("2024-01-01"),
    expiryDate: null,
    order: 1,
    createdAt: new Date(),
  },
  {
    id: "cert-3",
    title: "Google Cloud Digital Leader",
    issuer: "Google Cloud",
    description: "Foundational knowledge of cloud concepts, Google Cloud products, and digital transformation.",
    imageUrl: null,
    pdfUrl: null,
    verificationUrl: "https://cloud.google.com/certification/",
    issueDate: new Date("2023-11-01"),
    expiryDate: null,
    order: 2,
    createdAt: new Date(),
  },
  {
    id: "cert-4",
    title: "MongoDB Associate Developer",
    issuer: "MongoDB",
    description: "Proven ability to design and implement MongoDB applications and data models.",
    imageUrl: null,
    pdfUrl: null,
    verificationUrl: "https://mongodb.com/learn",
    issueDate: new Date("2023-09-01"),
    expiryDate: null,
    order: 3,
    createdAt: new Date(),
  },
];
